version: '3.4'

services:
  spacegame:
    image: florian4300/spacegame
    ports: 
        - 8080:8080
  
  
  highscoreapi:
    environment:
        ConnectionStrings__DefaultConnection: Server=db,1433;Database=HighscoreEntries;User Id=sa;Password=yourStrong(!)Password;
    image: florian4300/highscoreapi
    #build:
    #  context: .
    #  dockerfile: Dockerfile
    ports: 
        - 80:80
    depends_on:
        - db
  db:
      image: "mcr.microsoft.com/mssql/server"
      environment:
          SA_PASSWORD: "yourStrong(!)Password"
          ACCEPT_EULA: "Y"
      ports: 
            - 1433:1433